version: "2"

services:
  app:
    build: .
    container_name: control_panel
    command: python -u ./run.py
    restart: always
    ports:
      - "4000:4000"
    #volumes:
      #- .:/app
    networks:
      network1:
    environment:
      - "TERM=xterm"

    
networks:
  network1:
      external:
        name: network1